apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: rushane/webapp-image:1.2
        #ports:
        #- containerPort: 8080
        env:
        - name: OPENAI_SERVICE_URL
          #value: "172.18.77.57:30100"
          
          #since it is an interal call, port 8081. 30100 will not work
          value: "openapi-completionservice:8081"


---
apiVersion: v1
kind: Service
metadata:
  name: openapi-app

spec:

  selector:
    app: webapp

  ports:
    - name: http
      port: 8080
      nodePort: 30080

  type: NodePort
